FROM ghcr.io/linguaspark/server:main

COPY en-zh /app/models/en-zh

ENV MODELS_DIR=/app/models
ENV IP=0.0.0.0
ENV PORT=3000
# ENV ENV_API_KEY=
ENV RUST_LOG=info

EXPOSE 3000

ENTRYPOINT ["/app/linguaspark-server"]
